### ISSUE TITLE
HNSW memory footprint

### ISSUE THREAD

**Issue by funtusov** [nmslib/nmslib#104]
I am working with large image descriptors datasets (1e8-1e9 32-d vectors) and, based on initial tests, HNSW has an excellent scaling complexity. However, the problem arises from the memory footprint, and I am not sure whether this is the limitation of my usage, the method or, maybe, some inefficiency in the implementation.

I have read somewhere that a high-recall graph index is possible while taking around 20-40% of the dataset size in memory, but I see numbers around 300% (30gb of ram used after `addDataPoint()`, ~120gb of ram used after `createIndex()`).  

I use python bindings and the parameters in that particular case were M=15, ef=15, efConstruction=200,

Based on the paper, it should be taking around 15 \* 2 \* 130M vectors*(4-8) bytes which should traslate to 15-30gb

**Comment by yurymalkov** [comment]
Thank you for the tests.
At the default settings HNSW takes a lot of memory in case of L2 and cosine distance. This is because HNSW makes a full copy of index+data in the optimized form. This doubles the amount of memory used, but speeds up the search, especially when fast distance functions are used. In future the issue can be solved by building the optimized index from the scratch.

There are several workarounds at the moment. 
1) Do not build the optimized index by setting the "skip_optimized_index" build parameter to 1.
2) If you have a larger memory server available, you can build the optimized index, save it to disk and reload it later on a smaller memory machine. In this case only the optimized index containing all data will be loaded.

Another option is to reduce the M and maxM0 parameters. The memory consumption is mostly defined by the maxM0, and by default it is set to 2*M. Such selection usually results in getting higher performance at high accuracies, however in some cases maxM0 can be decreased to 1.5*M or even M without a significant loss in accuracy.

So, you can try to reduce M and/or set maxM0 to 1.5*M or M.

**Comment by searchivarius** [comment]
Hi @yurymalkov, Greg is saying that his memory footprint is 10x compared to what's possible. It's not clear how this happens, I am running some tests now.

**Comment by funtusov** [comment]
@yurymalkov thank you for the suggestions, I will run some tests with those amendments!

**Comment by searchivarius** [comment]
Dear @funtusov one more note. 

I have just finished running a test with 5M sift vectors (0.5KB per vector). After reading the data, I get 3.3 GB virtual and 2.7 GB resident, which seems to be ok, because data would use 2.5 GB. After creating an index with skip_optimized_index=1 and M=15, the memory footprint is: 5.7 GB virtual and 4.7 GB resident.

It's larger than expected, so we will have to investigate the issue more carefully in the future. Perhaps, it can be reduced.

Anyways, please, note that ``addDataPoint`` creates **a duplicate ** of the vector in memory. Therefore, one shouldn't keep vectors in the Python data structures, just read them one by one and pass to NMSLIB's ``addDataPoint``. For example, one can do this using the following function:
```
def read_data(fn):
    with open(fn) as f:
      for line in f:
        yield [float(v) for v in line.strip().split()]
```

**Comment by funtusov** [comment]
@searchivarius Thanks for the clarifications! Another potential improvement would be to be able to store data points with a user-defined type. For instance, I am using ORB descriptors, which are 256 bits, and OpenCV stores them as 32 8-bit integers, which could give a 4x memory reduction compared to a 32bit float

**Comment by searchivarius** [comment]
This is currently possible, but it requires implementing a custom space. It's a bit of a headache, but it's not overly complicated.

**Comment by funtusov** [comment]
@searchivarius Could you please point to the general direction (which custom space/at what step is it used)? Is it possible on the python side?

**Comment by searchivarius** [comment]
Unfortunately, this requires dabbling with C++ code first. A basic description is given regarding creating a space in C++ is given in https://github.com/searchivarius/nmslib/blob/master/docs/manual.pdf section 7.2 (creating a space). 

At the very least, one has to implement the function that creates an object from the string and the function that computes the distance.

Furthermore, a custom space isn't clearly supported by vector bindings. One has to use generic Python bindings (that pass only strings) or a query server.

**Comment by funtusov** [comment]
It dawned on me that the initial calculation of how much memory would the edges take (maxM0 = 30 * 130M vectors*(4-8) bytes) didn't include into account the enumeration of vertices. 

Am I right that for each edge we store the id's of two vertices + the measure of distance between them? So, it would take, say, 2*32-bit unsigned integers + a 32 bit float?

If that is the case, is there any theoretical way to store only some local references to the vertices, not global ones?

For cases where both the vectors and distances are quite small (i.e. 256-bit orb descriptors with hamming distance), storing the edge count dwarfs the datatset itself memory storage-wise.

**Comment by yurymalkov** [comment]
Hello Greg,
The distance between the vertices is not stored in memory. Only one id per link is stored (links possibly can be non-symmetrical).
We have not yet investigated the reason of the excessive memory usage during the construction. I think this may be an overhead of using c++ structures, but I am not sure. 
You can check the minimum memory footprint by looking at the disk size of stored hnsw index. It includes both data and the stored links and should be slightly bigger than you should predict by rough estimates. After saving/loading it should the memory usage should be reduced considerably.

**Comment by searchivarius** [comment]
Probably due to memory fragmentation one should multiply the minimum consumption by some coefficient (likely less than 2). A more compact version of the index can be created (or saved to disk and mmaped back), but it would require more work to implement.
