### ISSUE TITLE
problem compiling on windows

### ISSUE THREAD

**Issue by psarahdactyl** [nmslib/nmslib#295]
I am installing using pip3 and keep getting the following error when setup.py is running.

error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.11.25503\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by searchivarius** [comment]
Hi @psarahdactyl could you tell a bit more about your Visual studio  setup (i.e., what's the version)? Do you see additional errors? cl.exe is a compiler.

**Comment by psarahdactyl** [comment]
I am using Visual Studio Community 2017. I am using anaconda to create environments for different projects. I am using Python 3.6.4. It runs setup.py and there are a lot of C++ warnings that show up, and among them I see a few errors like:

> 
> nmslib\similarity_search\src\method\small_world_rand.cc(717): error C2065: '_MM_HINT_T0': undeclared identifier
>     nmslib\similarity_search\src\method\small_world_rand.cc(717): error C3861: '_mm_prefetch': identifier not found
>     nmslib\similarity_search\src\method\small_world_rand.cc(720): error C2065: '_MM_HINT_T0': undeclared identifier
>     nmslib\similarity_search\src\method\small_world_rand.cc(720): error C3861: '_mm_prefetch': identifier not found

And then I get the cl.exe one at the end.

**Comment by searchivarius** [comment]
@psarahdactyl thank you for the information! sorry, still hasn't gotten to fix this Windows stuff.

**Comment by psarahdactyl** [comment]
No worries, thanks for looking into it when you have the time!

**Comment by dipidoo** [comment]
I am excited to try this but I cannot install it on my machine due to the error above. It looks like `_mm_prefetch` is being used, it should be in intrin.h per [docs.microsoft.com](https://docs.microsoft.com/en-us/cpp/intrinsics/x64-amd64-intrinsics-list) but it seems that [only mm_intrin.h is included](https://github.com/nmslib/nmslib/search?utf8=%E2%9C%93&q=_mm_prefetch&type=) in the files that use `_mm_prefetch`.

If this doesn't fix, I know that [gcc has it in xmmintrin.h](https://github.com/gcc-mirror/gcc/blob/da8dff89fa9398f04b107e388cb706517ced9505/gcc/config/i386/xmmintrin.h) and that may be another thing to try.

This may have been due to [how it was in VS2010](https://msdn.microsoft.com/en-us/library/84szxsww(v=vs.100).aspx), where `_mm_prefetch` used to be in mmintrin.h.

I'd love to contribute myself but it may be a while until I find the time, I hope this helps to get closer to the resolution.

**Comment by searchivarius** [comment]
@dipidoo I wonder why our Windows build doesn't fail.

**Comment by benfred** [comment]
@searchivarius I don't think the windows CI is working - the appveyor link on the readme still points to the 'searchivarious/nmslib' repo and hasn't run since we moved to the nmslib organization =(.

This should be fixed with the previous commit

**Comment by searchivarius** [comment]
@benfred many thanks!
