### ISSUE TITLE
non-metric example

### ISSUE THREAD

**Issue by bkj** [nmslib/nmslib#314]
Hi --

Are there any example scripts showing search in a non-metric space?  The ones I can find in eg. the python notebooks all look like they're using l2/cosine/etc. 

Thanks

**Comment by searchivarius** [comment]
I will publish some latest scripts online. It's probably even worth creating another Python book. Which spaces do you think would be most interesting?

**Comment by bkj** [comment]
I don't have a good sense of the kinds of problems that a good non-metric search index would help solve -- so I defer to you on what's most interesting!  (at least for now...)

**Comment by searchivarius** [comment]
Hi @bkj I have added a basic metric example here: https://github.com/nmslib/nmslib/tree/master/python_bindings/notebooks

Problem is that current implementations of graph based method aren't very good at handling non-symmetric distances. SW-graph should be ok though, but I have no idea about HNSW  (haven't tested it yet). There are also improvements for SW-graph (for non-symmetric distances) that I haven't pushed to master yet.

**Comment by bkj** [comment]
Related to this -- if I wanted to implement my own non-metric space, where would the place to start be?

Specifically, I'd be interested in being able to use NMSLIB for dynamic time warping.  DTW is symmetric (I think?), but doesn't satisfy the triangle inequality.

**Comment by searchivarius** [comment]
@bkj a somewhat description of the process is given in the manual. However, the best thing to do is to take a dummy space and to implement all the necessary functions:
https://github.com/nmslib/nmslib/blob/master/similarity_search/include/space/space_dummy.h
**You should also register this space in the factory (this is described in the manual)**
One little note on de/serialization. API uses strings, but nobody actually prevents you from putting binary objects into strings, because C++ can keep arbitrary binary objects as well.

**Comment by searchivarius** [comment]
@bkj also checking some of the other space's implementation can be useful, e.g., you can see how the vector space is implemented.
