### ISSUE TITLE
How do we know the size of the graph in memory after we call LoadIndex?

### ISSUE THREAD

**Issue by vamshin** [nmslib/nmslib#395]
Hi searchivarius@,

Is there a way to know the memory consumption of the graph once loaded onto memory?

Usecase:-
I am trying to keep graphs which of certain size in memory and delete the smaller graphs right  away after usage

**Comment by searchivarius** [comment]
Hi @vamshin there's no direct API call for this. It's not difficult to implement the one that would estimate the size. However, it is difficult to know for sure due to all the fragmentation issues. That said on many OS you can surely estimate the amount of memory used by the program. So, you can estimate the footprint, load the graph, estimate the footprint and compute the difference.
