### ISSUE TITLE
L1 optimized index

### ISSUE THREAD

**Issue by Elbek-Khoshimjonov** [nmslib/nmslib#456]
Appreciate all the contributors!

nmslib is used by [elasticsearch-kNN](https://github.com/opendistro-for-elasticsearch/k-NN). I was using that repo for my project. 
But I want to use `l1` distance instead of `l2` or `cosinesimil`, but I have noticed that they don't support `l1` distance because nmslib does not support optimized index saving for spaces except `l2` or `cosinesimil`.

I have tried from this [issue and comment](https://github.com/nmslib/nmslib/issues/356#issuecomment-634406332) to implement `l1` distance.
 But because data is stored in a separate file, I/O-latency (which is biggest) doubles for every query.

So I am asking L1-optimized index as `L2`.

**Comment by searchivarius** [comment]
Hi @Elbek-Khoshimjonov we are adding better support for the inner product search right now. Because we have simplified the code, actually, we can easily add L1 too. However, we cannot currently resolve the issue related to saving/loading extra data. I mean L1 will be like the current L2 implementation if this makes sense.

**Comment by Elbek-Khoshimjonov** [comment]
If L1 implementation is similar to L2, I think we can use it in elasticsearch. Thanks Leonid.

**Comment by searchivarius** [comment]
It's not implemented yet, but I am going to do this shortly.

**Comment by searchivarius** [comment]
Sorry about the delay, but this is now resolved at least in this repo.

**Comment by Elbek-Khoshimjonov** [comment]
Great news, thanks @searchivarius
